# Site settings
title: OpenAerialMap
description: "Imagery from satellites, unmanned aerial vehicles (UAVs) and other aircraft is becoming increasingly available after a disaster. It is often difficult to determine what is available and easily access it. OpenAerialMap (OAM) seeks to solve this by providing a simple open way to process and provide imagery for humanitarian response and disaster preparedness. There have been multiple tries to start OpenAerialMap in the past. This current interation is being started by the Humanitarian OpenStreetMap team and partners through the gracious support of the Humanitarian Innovation Fund."
baseurl: "/OpenAerialMap"

github_username:  hotosm

# Build settings
markdown: kramdown

kramdown:
  input: GFM

permalink: pretty
pygments: true

safe: true
